name: 'Link Checker'
description: 'An action for link checking repository Markdown and HTML files'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'external-link'  
  color: 'purple'
outputs:
  result: 
    description: The output of the link checker
